export default {
    inputBlockWrap: 'form-group',
    label: '',
    input: 'form-control',
    standard: '',
    errored: 'is-invalid',
    inlineWrap: 'form-group',
    itemHeader: '',
    button: 'btn btn-primary',
    checkboxWrap: 'form-check',
    radioGroupWrap: '',
    radioWrap: 'form-check',
    checkboxLabel: 'form-check-label',
    radioLabel: 'form-check-label',
    radio: 'form-check-input',
    checkbox: 'form-check-input',
    error: 'w2d-invalid-feedback',
    errorIcon: '',
    select: 'form-control',
    table: 'table',
    panel: 'card',
    title: 'card-header',
    content: 'card-body',
    contentMargin: ''
  }